import assert from 'node:assert/strict';
import { companyRoster } from './company-roster';
import { assignEmployeeCodes } from './people';
import type { Person } from '@/components/dashboard/roster';
const existing: Person = { id: 'existing', employeeCode: 'SOR-0001', name: 'Edited name', email: 'same@example.test', role: 'LEAD', stores: ['Costco 1018'], team: 'Existing team', attendance: 95, weeklyProfit: [123], status: 'retired' };
const account = { id: 'account-1', employeeId: 'LEAD-0001', name: 'Original name', email: 'SAME@example.test', role: 'LEAD' };
assert.deepEqual(companyRoster([existing], [], [account]), [existing], 'matching account cannot replace names, status, teams, or history');
const next = companyRoster([existing], [], [{ ...account, id: 'new', employeeId: 'SOR-0002', email: 'new@example.test', name: 'Edited name' }]);
assert.equal(next.length, 2);
assert.equal(next[1].employeeCode, 'SOR-0002');
assert.equal(next[1].name, 'Edited name (SOR-0002)', 'same names do not merge identities');
assert.equal(next[1].role, 'LEAD');
assert.deepEqual(companyRoster(next, [], [{ ...account, id: 'new', employeeId: 'SOR-0002', email: 'new@example.test' }]), next, 'projection is idempotent');
const profiles = [{ id: 'profile', employeeCode: 'REP-123456', displayName: 'Report person', email: null, status: 'ACTIVE', title: 'OWNER', storeName: null, teamName: 'Should not join' }];
assert.equal(companyRoster([], profiles, [])[0].team, '');
assert.deepEqual(companyRoster([], [], []), []);
assert.equal(existing.name, 'Edited name');
assert.equal(assignEmployeeCodes([{ ...existing, employeeCode: 'LEAD-MARKETABC' }])[0].employeeCode, 'LEAD-MARKETABC');
console.log('Company roster: immutable joins, duplicate names, new accounts, owner isolation, and data preservation passed');
