import { SaleEntry, Period, aggregateSales, PersonStats } from './sales';
import { CommissionState } from '@/components/dashboard/editable-sections';
import { Person } from '@/components/dashboard/roster';
import { TeamData } from '@/components/dashboard/editable-sections';

// Pay model (owner's rules, all editable in the Commission tab's Role Structure):
//   • Rep / Intern — base commission on their own sales (the rep cut).
//   • Lead — base on their OWN sales + a per-line BUMP on their own lines.
//     A lead does NOT earn off the reps; they just make a few dollars more
//     per line for themselves.
//   • ASM / AD — paid like a Lead on their OWN lines ($45), PLUS an override
//     off their team's whole production (3% of generated by default).
//   • Market Owner — the remainder, computed by computeOfficeTake().

export interface PayBreakdown {
  base: number;      // rep commission on own sales
  bump: number;      // lead per-line bonus on own lines
  override: number;  // ASM override off team production
  total: number;
  lines: number;     // own phone lines
  teamRevenue: number; // team office generated (ASM only)
  notes: string[];
}

// Role rules are matched by their (owner-editable) display name, so the
// patterns have to be precise. The previous ASM pattern was /asm|ad\b/i, which
// also matches "Le-ad" — and since .find() takes the first hit, every ASM
// lookup silently returned the LEAD rule. ASMs were therefore paid $5 per team
// line instead of 3% of team revenue. Anchor the Lead pattern and drop the
// "ad" alternative so each role can only resolve to itself.
const RULE_PATTERNS = {
  rep: /^(sales )?rep|intern/i,
  lead: /^lead/i,
  asm: /asm/i,
  owner: /owner/i,
} as const;

function findRule(commission: CommissionState, key: keyof typeof RULE_PATTERNS) {
  return commission.roles?.find(r => RULE_PATTERNS[key].test(r.name));
}

function loadTeams(): TeamData[] {
  if (typeof window === 'undefined') return [];
  try { return JSON.parse(localStorage.getItem('se-teams-v2') || '[]'); } catch { return []; }
}

export function computePay(
  person: Person,
  ctx: { sales: SaleEntry[]; commission: CommissionState; people: Person[]; period: Period }
): PayBreakdown {
  const agg = aggregateSales(ctx.sales, ctx.commission, { period: ctx.period });
  const statsByName = new Map(agg.perPerson.map(p => [p.person.toLowerCase(), p]));
  const own = statsByName.get(person.name.toLowerCase());

  const base = own?.commission ?? 0;
  const lines = own?.lines ?? 0;
  const notes: string[] = [];
  let bump = 0;
  let override = 0;
  let teamRevenue = 0;

  if (person.role === 'LEAD') {
    const rule = findRule(ctx.commission, 'lead');
    const perLine = rule?.amount ?? 0;
    bump = perLine * lines;
    if (perLine > 0) notes.push(`Lead bump: ${lines} own lines × $${perLine} = $${bump.toFixed(0)}`);
  }

  if (person.role === 'ASM') {
    const rule = findRule(ctx.commission, 'asm');
    // An ASM is paid like a Lead on their OWN lines ($40 base + $5 = $45) AND
    // takes a percentage of their whole team. Previously only the override was
    // applied, so an ASM who sold personally was underpaid on every line.
    const ownPerLine = rule?.perLine ?? 0;
    bump = ownPerLine * lines;
    if (ownPerLine > 0) notes.push(`ASM own-line bump: ${lines} lines × $${ownPerLine} = $${bump.toFixed(0)}`);
    const teams = loadTeams();
    // Teams this ASM oversees (their name is in the ASM slot)
    const myTeams = teams.filter(t => t.asm?.toLowerCase() === person.name.toLowerCase());
    const memberNames = new Set<string>();
    myTeams.forEach(t => {
      ctx.people.filter(p => p.team === t.name).forEach(p => memberNames.add(p.name.toLowerCase()));
      if (t.lead) memberNames.add(t.lead.toLowerCase());
    });
    let teamLines = 0;
    memberNames.forEach(n => {
      const s = statsByName.get(n);
      if (s) { teamRevenue += s.revenue; teamLines += s.lines; }
    });
    const amt = rule?.amount ?? 0;
    const unit = rule?.unit ?? '';
    if (/%/.test(unit)) {
      override = (amt / 100) * teamRevenue;
      if (amt > 0) notes.push(`ASM override: ${amt}% of $${teamRevenue.toFixed(0)} team generated = $${override.toFixed(0)}`);
    } else {
      override = amt * teamLines;
      if (amt > 0) notes.push(`ASM override: ${teamLines} team lines × $${amt} = $${override.toFixed(0)}`);
    }
  }

  return { base, bump, override, total: base + bump + override, lines, teamRevenue, notes };
}

export interface OfficeTake {
  generated: number;   // office payout AT&T deposits
  repPay: number;      // every rep's base commission
  leadBumps: number;   // per-line bumps for Leads and ASMs on their own lines
  asmOverrides: number;// percentage overrides off team production
  chargebacks: number; // GPS late clock-out charges recouped
  owner: number;       // what is actually left for the office
  margin: number;      // owner as a % of generated
}

// The owner is not a fixed cut — they keep whatever survives after the floor is
// paid. Computing it here means the P&L can never drift from the pay engine.
export function computeOfficeTake(
  ctx: { sales: SaleEntry[]; commission: CommissionState; people: Person[]; period: Period }
): OfficeTake {
  const agg = aggregateSales(ctx.sales, ctx.commission, { period: ctx.period });
  const generated = agg.revenue;
  const repPay = agg.commission;

  let leadBumps = 0;
  let asmOverrides = 0;
  for (const person of ctx.people) {
    if (person.role !== 'LEAD' && person.role !== 'ASM') continue;
    const pay = computePay(person, ctx);
    leadBumps += pay.bump;
    asmOverrides += pay.override;
  }

  const owner = generated - repPay - leadBumps - asmOverrides;
  return {
    generated,
    repPay,
    leadBumps,
    asmOverrides,
    chargebacks: agg.chargebacks,
    owner,
    margin: generated > 0 ? (owner / generated) * 100 : 0,
  };
}
