import assert from 'node:assert/strict';
import { aggregateSales, inPeriod, todayStr, type SaleEntry } from './sales';
import { DEFAULT_COMMISSION } from '../components/dashboard/editable-sections';
const row: SaleEntry = { id: 'a', date: todayStr(), person: 'Rep', store: 'Costco 1018', plan: 'Value 2.0', qty: 1, nextUps: 0, insurance: 0 };
const entries = [row, { ...row, id: 'b', date: todayStr(-1), qty: 2 }, { ...row, id: 'c', date: todayStr(-7), qty: 4 }, { ...row, id: 'd', date: todayStr(-30), qty: 8 }];
const total = (period: 'daily' | 'weekly' | 'monthly' | 'all') => aggregateSales(entries, DEFAULT_COMMISSION, { period });
assert.equal(total('daily').lines, 1);
assert.equal(total('weekly').lines, 3);
assert.equal(total('monthly').lines, 7);
assert.equal(total('all').lines, 15);
assert.equal(aggregateSales(entries, DEFAULT_COMMISSION, { period: 'monthly', date: todayStr(-7) }).lines, 4);
assert.equal(aggregateSales(entries, DEFAULT_COMMISSION, { period: 'all', stores: ['Target 100'] }).lines, 0);
assert.equal(total('weekly').perPerson[0].revenue, total('weekly').revenue);
assert.equal([...total('weekly').perPlan.values()].reduce((sum, plan) => sum + plan.revenue, 0), total('weekly').revenue);
assert.equal(aggregateSales([{ ...row, plan: 'P' }], DEFAULT_COMMISSION, { period: 'daily' }).premium, 1);
assert.equal(aggregateSales([{ ...row, plan: 'X' }], DEFAULT_COMMISSION, { period: 'daily' }).lines, 1);
assert.equal(inPeriod(todayStr(1), 'weekly'), false);
assert.equal(inPeriod('invalid', 'weekly'), false);
console.log('Production windows: daily, 7-day, 30-day, all-time, exact dates, stores, and matching totals passed');
